name: travsy
description: "Description"
publish_to: 'none'
maintainer: "Habibullah Bahar <https://github.com/iHabibullahBahar>"
repository: https://github.com/iHabibullahBahar/travsy_ai_app.git

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  gap: ^3.0.1
  intro_screen_onboarding_flutter: ^1.0.0
  pinput: ^4.0.0
  fancy_shimmer_image: ^2.0.3
  image_picker: ^1.0.8
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-alpha.3
  flutter_inappwebview: ^6.0.0
  onesignal_flutter: ^5.2.0
  flutter_masonry_view: ^0.0.2
  http: ^1.2.0
  device_frame: ^1.1.0
  percent_indicator: ^4.2.3
  loading_indicator: ^3.1.1
  wheel_slider: ^1.2.1
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/images/image_for_test/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

