// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6tRUssRu1_OWfAUUBn_s0BXBhvAhZBc',
    appId: '1:883521084883:web:58ec89d6c64fe2c99a6326',
    messagingSenderId: '883521084883',
    projectId: 'travsy-ai',
    authDomain: 'travsy-ai.firebaseapp.com',
    storageBucket: 'travsy-ai.appspot.com',
    measurementId: 'G-YWFZY65NQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRbpjLffQ2CWHQtXF512l8H-DyZ-di4E',
    appId: '1:883521084883:android:0ce42d3039cd393e9a6326',
    messagingSenderId: '883521084883',
    projectId: 'travsy-ai',
    storageBucket: 'travsy-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4QafsK_7NfMUv8xf6fLZpyuHGN3QMbTw',
    appId: '1:883521084883:ios:b9e87538099f6fce9a6326',
    messagingSenderId: '883521084883',
    projectId: 'travsy-ai',
    storageBucket: 'travsy-ai.appspot.com',
    iosBundleId: 'com.travsy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4QafsK_7NfMUv8xf6fLZpyuHGN3QMbTw',
    appId: '1:883521084883:ios:b9e87538099f6fce9a6326',
    messagingSenderId: '883521084883',
    projectId: 'travsy-ai',
    storageBucket: 'travsy-ai.appspot.com',
    iosBundleId: 'com.travsy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB6tRUssRu1_OWfAUUBn_s0BXBhvAhZBc',
    appId: '1:883521084883:web:242d92577114f1499a6326',
    messagingSenderId: '883521084883',
    projectId: 'travsy-ai',
    authDomain: 'travsy-ai.firebaseapp.com',
    storageBucket: 'travsy-ai.appspot.com',
    measurementId: 'G-8TRHHDEDMC',
  );
}
